api_token_var: foo

llm:
  base_url: http://localhost:8000/v1
  model: *


agent:
  task: |-
    Your task is to play pokerogue and try to beat the game.
    Actions are made by keystrokes. 
    'space' - confirm
    'backspace' - back
    arrow keys ('up', 'down', 'left', 'right') - move up down left right
    Mouse is not usable in this game.

    You can catch new pokemon to assemble a strong team.
    Between fights you can pick and buy rewards.
    To proceed through dialogue, press space.
    Good luck.
