api_token_var: foo

browser_binary_path: /snap/bin/chromium

llm:
  base_url: http://localhost:8000/v1
  model: '*'

agent:
  task: |-
    Your task is to play pokerogue and try to beat the game.
    Actions are made by the following inputs: 
    'space' - confirm
    'backspace' - back
    'up', 'down', 'left', 'right' - move in given directions 
